### PR TITLE
Minor wording change

### PR DESCRIPTION
**Pull request by connorgallopo**
Changed `all` to `and` in the Readme.md

### CODE REVIEW

**Review by garettarrowood — CHANGES_REQUESTED** [review]
Factories look good.  But the `post` spec still has a bunch of `let`s and `before`s in it. And the `author` spec is still creating authors.

Any suggestions on making my instructions more clear?  This needs more than a green test suite.

**Comment by connorgallopo** [comment]
These changes should not have made it into this branch. This PR was only supposed to be a wording change. Also can we wright a spec against the spec file to look for let to not be used?

**Comment by garettarrowood** [comment]
Maybe? I've actually not looked into it.  Next week I'll take a look.

**Comment by garettarrowood** [comment]
In hindsight, I actually did look into this and couldn't find a way to detect if and how many `let`s were getting invoked in a spec file.

**Comment by garettarrowood** [comment]
I've updated this repo with tests that break with the use of `let` and `Model.new` and `Model.create`. Could you redo this lab? Don't forget to create an upstream remote and pull the most recent changes first :).

**Pull request closed without merging**
